version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/logger"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Logger"
  - package-ecosystem: "npm"
    directory: "/elysia-request-id"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Elysia-Request-ID"
