name: "[Logger] Publish to JSR"

defaults:
  run:
    working-directory: ./packages/logger

on:
  push:
    paths:
      - "packages/logger/**"
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Use PNPM Package Manager
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install --frozen-lockfile
      - run: pnpm dlx jsr publish
